# Generated by Django 4.1.5 on 2023-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='_zip',
            field=models.CharField(default='-', max_length=7),
            preserve_default=False,
        ),
    ]
